Resource Types and Organization Types
rice-apps/thi-walk30 pull request #4
Opened 2023-11-04 19:58 UTC by MacAjwani

Created and tested schemas and routes for organization and resource types

2023-11-04 20:24 UTC, ch5zzy requested changes

2023-11-04 20:24 UTC, ch5zzy commented on server/.env.sample
Can you restore this file?

2023-11-04 20:24 UTC, ch5zzy commented on server/routes/resource.js
> +router.patch('/:link', async(req,res) =>{
Can you change `:link` to `:id` and have this update by ID instead?

2023-11-04 20:24 UTC, ch5zzy commented on server/routes/resource.js
> +router.delete('/:link', async(req, res) => {
Same as with the PATCH route. Update `:link` to `:id`.

2023-11-04 20:24 UTC, ch5zzy commented on server/package-lock.json
Can you restore this file? I think if you run `npm i` it will be regenerated.

2023-11-04 20:24 UTC, ch5zzy commented on server/models/resource.js
> +    ft_img: {
Can you change this to `featured_img`? Just to be more consistent with `featured_img` in the Event type.

2023-11-04 20:24 UTC, ch5zzy commented on server/.env.sample
Can you restore this file?

2023-11-04 20:24 UTC, ch5zzy commented on node_modules/.package-lock.json
Can you delete this `node_modules` folder from the root of the project?

2023-11-04 20:25 UTC, ch5zzy commented on app/App.tsx
Can you remove all the changes you made in the `app` directory? Since this PR is just related to server changes.

2023-11-11 19:30 UTC, nolantuite approved these changes
lgtm!

2023-11-11 20:16 UTC, merged